In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.datasets import load_iris
iris = load_iris()

In [3]:
print(f'Features names is:{iris.feature_names}')

Features names is:['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [4]:
print(f'Target names is:{iris.target_names}')

Target names is:['setosa' 'versicolor' 'virginica']


In [5]:
print(f'The data for the features are as:\n{iris.data[0:5]}')

The data for the features are as:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [6]:
print(f'Target for the given features are as:\n{iris.target[0:5]}')

Target for the given features are as:
[0 0 0 0 0]


In [7]:
#Create a dataframe from the iris dataset
df_iris = pd.DataFrame(data=iris.data,columns=iris.feature_names)
df_iris.head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [8]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
df_iris['species'] = pd.Categorical.from_codes(iris.target,iris.target_names)

In [10]:
df_iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [11]:
X = df_iris.drop('species',axis = 1)
y = df_iris['species']

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=101,test_size=0.2)

In [13]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=5)

In [14]:
model.fit(X_train,y_train)

KNeighborsClassifier()

In [18]:
predictions = model.predict(X_test)
predictions

array(['setosa', 'setosa', 'setosa', 'virginica', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa',
       'virginica', 'setosa', 'setosa', 'virginica', 'virginica',
       'versicolor', 'versicolor', 'versicolor', 'setosa', 'virginica',
       'versicolor', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'virginica', 'setosa', 'setosa'],
      dtype=object)

In [20]:
y_test.values

['setosa', 'setosa', 'setosa', 'virginica', 'versicolor', ..., 'versicolor', 'versicolor', 'virginica', 'setosa', 'setosa']
Length: 30
Categories (3, object): ['setosa', 'versicolor', 'virginica']

In [21]:
from sklearn.metrics import accuracy_score
score = accuracy_score(predictions,y_test)

In [22]:
print(f'Accuracy is:{score}')

Accuracy is:1.0


In [24]:
print(f'Total Correct prediction is:{accuracy_score(predictions,y_test,normalize=False)}')

Total Correct prediction is:30.0


In [30]:
print(f'Total Incorrect prediction is:{len(predictions) - accuracy_score(predictions,y_test,normalize=False)}')

Total Incorrect prediction is:0.0
